In [1]:
from google.colab import files
uploaded = files.upload()

Saving full_dataset.csv to full_dataset.csv

In [2]:
import pandas as pd
df = pd.read_csv("full_dataset.csv")
print(df)

                     id                                         subject  \
0        promotions_582       Anniversary Special: Buy one get one free
1             spam_1629              Your Amazon was used on new device
2              spam_322                         Re: Your Google inquiry
3       social_media_80              Digital Ritual Experience Creation
4            forum_1351       Your post was moved to "Programming Help"
...                 ...                                             ...
13472  social_media_817                     News from groups you follow
13473   verify_code_368          Identity verification required: 756179
13474         forum_898  Moderation notice: Community Guidelines update
13475         spam_2152               Renew Google subscription 80% off
13476   promotions_1900             Early access: Summer sale start now

                                                    body  \
0      As our loyal customer, get exclusive $60 off $...
1      Your $5000 refund is processed. Claim: bit.ly/...
2      Hi, following up about your Google application...
3      Cross-cultural ceremony design. Join: virtualr...
4      Trending: "cooking" (258 comments). View: supp...
...                                                  ...
13472  Alex: "Anyone free this weekend?" Lisa: "Count...
13473  Your access code is 907472 for transaction aut...
13474  Trending: "cooking" (258 comments). View: supp...
13475  Your package couldn't be delivered. Tracking# ...
13476  Final hours of biggest sale. Up to 30% off: ex...

                                                    text      category  \
0      Anniversary Special: Buy one get one free As o...    promotions
1      Your Amazon was used on new device Your $5000 ...          spam
2      Re: Your Google inquiry Hi, following up about...          spam
3      Digital Ritual Experience Creation Cross-cultu...  social_media
4      Your post was moved to "Programming Help" Tren...         forum
...                                                  ...           ...
13472  News from groups you follow Alex: "Anyone free...  social_media
13473  Identity verification required: 756179 Your ac...   verify_code
13474  Moderation notice: Community Guidelines update...         forum
13475  Renew Google subscription 80% off Your package...          spam
13476  Early access: Summer sale start now Final hour...    promotions

       category_id
0                1
1                3
2                3
3                2
4                0
...            ...
13472            2
13473            5
13474            0
13475            3
13476            1

[13477 rows x 6 columns]

In [35]:
df.shape

(10034, 3)

In [44]:
duplicate_count = df.duplicated(subset=['clean_text']).sum()
print("Duplicate count:", duplicate_count)

Duplicate count: 0

In [45]:
total_count = len(df)
duplicate_count = df.duplicated(subset=['clean_text']).sum()
final_count = total_count - duplicate_count

print("Total dataset size:", total_count)
print("Duplicate count:", duplicate_count)
print("Dataset size after removing duplicates:", final_count)

Total dataset size: 10034
Duplicate count: 0
Dataset size after removing duplicates: 10034

In [34]:
df.columns

Index(['clean_text', 'category', 'urgency'], dtype='object')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13477 entries, 0 to 13476
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           13477 non-null  object
 1   subject      13477 non-null  object
 2   body         13477 non-null  object
 3   text         13477 non-null  object
 4   category     13477 non-null  object
 5   category_id  13477 non-null  int64
dtypes: int64(1), object(5)
memory usage: 631.9+ KB

In [15]:
df.isnull().sum()

text          0
category      0
clean_text    0
dtype: int64

In [46]:
df = df.dropna()
df.isnull().sum()

clean_text    0
category      0
urgency       0
dtype: int64

In [4]:
df = df[["text","category"]]
print(df)

                                                    text      category
0      Anniversary Special: Buy one get one free As o...    promotions
1      Your Amazon was used on new device Your $5000 ...          spam
2      Re: Your Google inquiry Hi, following up about...          spam
3      Digital Ritual Experience Creation Cross-cultu...  social_media
4      Your post was moved to "Programming Help" Tren...         forum
...                                                  ...           ...
13472  News from groups you follow Alex: "Anyone free...  social_media
13473  Identity verification required: 756179 Your ac...   verify_code
13474  Moderation notice: Community Guidelines update...         forum
13475  Renew Google subscription 80% off Your package...          spam
13476  Early access: Summer sale start now Final hour...    promotions

[13477 rows x 2 columns]

In [29]:
print("Number of categories:", df['category'].nunique())

Number of categories: 6

In [30]:
print(df['category'].value_counts())

category
social_media    1998
spam            1914
updates         1798
forum           1742
verify_code     1331
promotions      1251
Name: count, dtype: int64

In [6]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [7]:
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

True

In [8]:
#Lowercase
df["clean_text"] = df["text"].str.lower()
df

,text,category,clean_text
0,Anniversary Special: Buy one get one free As o...,promotions,anniversary special: buy one get one free as o...
1,Your Amazon was used on new device Your $5000 ...,spam,your amazon was used on new device your $5000 ...
2,"Re: Your Google inquiry Hi, following up about...",spam,"re: your google inquiry hi, following up about..."
3,Digital Ritual Experience Creation Cross-cultu...,social_media,digital ritual experience creation cross-cultu...
4,"Your post was moved to ""Programming Help"" Tren...",forum,"your post was moved to ""programming help"" tren..."
...,...,...,...
13472,"News from groups you follow Alex: ""Anyone free...",social_media,"news from groups you follow alex: ""anyone free..."
13473,Identity verification required: 756179 Your ac...,verify_code,identity verification required: 756179 your ac...
13474,Moderation notice: Community Guidelines update...,forum,moderation notice: community guidelines update...
13475,Renew Google subscription 80% off Your package...,spam,renew google subscription 80% off your package...
13476,Early access: Summer sale start now Final hour...,promotions,early access: summer sale start now final hour...

In [9]:
#Remove Special Characters And Numbers
df["clean_text"] = df["clean_text"].str.replace(r'[^a-z\s]','', regex=True)
df

,text,category,clean_text
0,Anniversary Special: Buy one get one free As o...,promotions,anniversary special buy one get one free as ou...
1,Your Amazon was used on new device Your $5000 ...,spam,your amazon was used on new device your refun...
2,"Re: Your Google inquiry Hi, following up about...",spam,re your google inquiry hi following up about y...
3,Digital Ritual Experience Creation Cross-cultu...,social_media,digital ritual experience creation crosscultur...
4,"Your post was moved to ""Programming Help"" Tren...",forum,your post was moved to programming help trendi...
...,...,...,...
13472,"News from groups you follow Alex: ""Anyone free...",social_media,news from groups you follow alex anyone free t...
13473,Identity verification required: 756179 Your ac...,verify_code,identity verification required your access co...
13474,Moderation notice: Community Guidelines update...,forum,moderation notice community guidelines update ...
13475,Renew Google subscription 80% off Your package...,spam,renew google subscription off your package co...
13476,Early access: Summer sale start now Final hour...,promotions,early access summer sale start now final hours...

In [10]:
#Remove Extra Spaces
df["clean_text"] = df["clean_text"].str.replace(r'\s+',' ',regex=True).str.strip()
df

,text,category,clean_text
0,Anniversary Special: Buy one get one free As o...,promotions,anniversary special buy one get one free as ou...
1,Your Amazon was used on new device Your $5000 ...,spam,your amazon was used on new device your refund...
2,"Re: Your Google inquiry Hi, following up about...",spam,re your google inquiry hi following up about y...
3,Digital Ritual Experience Creation Cross-cultu...,social_media,digital ritual experience creation crosscultur...
4,"Your post was moved to ""Programming Help"" Tren...",forum,your post was moved to programming help trendi...
...,...,...,...
13472,"News from groups you follow Alex: ""Anyone free...",social_media,news from groups you follow alex anyone free t...
13473,Identity verification required: 756179 Your ac...,verify_code,identity verification required your access cod...
13474,Moderation notice: Community Guidelines update...,forum,moderation notice community guidelines update ...
13475,Renew Google subscription 80% off Your package...,spam,renew google subscription off your package cou...
13476,Early access: Summer sale start now Final hour...,promotions,early access summer sale start now final hours...

In [11]:
#Remove Stopwords
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
df["clean_text"] = df["clean_text"].apply(
    lambda x: " ".join(word for word in x.split() if word not in stop_words)
)
df

,text,category,clean_text
0,Anniversary Special: Buy one get one free As o...,promotions,anniversary special buy one get one free loyal...
1,Your Amazon was used on new device Your $5000 ...,spam,amazon used new device refund processed claim ...
2,"Re: Your Google inquiry Hi, following up about...",spam,google inquiry hi following google application...
3,Digital Ritual Experience Creation Cross-cultu...,social_media,digital ritual experience creation crosscultur...
4,"Your post was moved to ""Programming Help"" Tren...",forum,post moved programming help trending cooking c...
...,...,...,...
13472,"News from groups you follow Alex: ""Anyone free...",social_media,news groups follow alex anyone free weekend li...
13473,Identity verification required: 756179 Your ac...,verify_code,identity verification required access code tra...
13474,Moderation notice: Community Guidelines update...,forum,moderation notice community guidelines update ...
13475,Renew Google subscription 80% off Your package...,spam,renew google subscription package couldnt deli...
13476,Early access: Summer sale start now Final hour...,promotions,early access summer sale start final hours big...

In [12]:
nltk.download('stopwords', quiet=True)
stop_words = set(stopwords.words('english'))
print(f"Loaded {len(stop_words)} stopwords")

Loaded 198 stopwords

In [13]:
#Lemmatization
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
df["clean_text"] = df["clean_text"].apply(
    lambda x: " ".join(lemmatizer.lemmatize(word) for word in x.split())
)
df

,text,category,clean_text
0,Anniversary Special: Buy one get one free As o...,promotions,anniversary special buy one get one free loyal...
1,Your Amazon was used on new device Your $5000 ...,spam,amazon used new device refund processed claim ...
2,"Re: Your Google inquiry Hi, following up about...",spam,google inquiry hi following google application...
3,Digital Ritual Experience Creation Cross-cultu...,social_media,digital ritual experience creation crosscultur...
4,"Your post was moved to ""Programming Help"" Tren...",forum,post moved programming help trending cooking c...
...,...,...,...
13472,"News from groups you follow Alex: ""Anyone free...",social_media,news group follow alex anyone free weekend lis...
13473,Identity verification required: 756179 Your ac...,verify_code,identity verification required access code tra...
13474,Moderation notice: Community Guidelines update...,forum,moderation notice community guideline update t...
13475,Renew Google subscription 80% off Your package...,spam,renew google subscription package couldnt deli...
13476,Early access: Summer sale start now Final hour...,promotions,early access summer sale start final hour bigg...

In [14]:
df[["text","clean_text"]].head()

,text,clean_text
0,Anniversary Special: Buy one get one free As o...,anniversary special buy one get one free loyal...
1,Your Amazon was used on new device Your $5000 ...,amazon used new device refund processed claim ...
2,"Re: Your Google inquiry Hi, following up about...",google inquiry hi following google application...
3,Digital Ritual Experience Creation Cross-cultu...,digital ritual experience creation crosscultur...
4,"Your post was moved to ""Programming Help"" Tren...",post moved programming help trending cooking c...

In [22]:
high_keywords = ['urgent', 'immediately', 'asap', 'emergency', 'expires today',
                 'unauthorized', 'fraud', 'suspended', 'blocked', 'critical',
                 'action required', 'password', 'reset', 'alert', 'warning']

medium_keywords = ['response needed', 'attention', 'due', 'schedule', 'appointment',
                   'meeting', 'invoice', 'payment', 'request', 'confirm']

low_keywords = ['newsletter', 'news', 'weekly', 'announcement', 'tips',
                'offer', 'deal', 'promotion', 'welcome', 'notification']

urgency_list = []

for index, row in df.iterrows():
    combined = str(row['text']).lower()

    high_count = sum(1 for kw in high_keywords if kw in combined)
    medium_count = sum(1 for kw in medium_keywords if kw in combined)
    low_count = sum(1 for kw in low_keywords if kw in combined)

    if high_count > medium_count and high_count > low_count:
        urgency_list.append('high')
    elif medium_count > low_count:
        urgency_list.append('medium')
    else:
        urgency_list.append('low')

df['urgency'] = urgency_list
df

,text,category,clean_text,urgency
0,Anniversary Special: Buy one get one free As o...,promotions,anniversary special buy one get one free loyal...,low
1,Your Amazon was used on new device Your $5000 ...,spam,amazon used new device refund processed claim ...,low
2,"Re: Your Google inquiry Hi, following up about...",spam,google inquiry hi following google application...,low
3,Digital Ritual Experience Creation Cross-cultu...,social_media,digital ritual experience creation crosscultur...,low
4,"Your post was moved to ""Programming Help"" Tren...",forum,post moved programming help trending cooking c...,low
...,...,...,...,...
13472,"News from groups you follow Alex: ""Anyone free...",social_media,news group follow alex anyone free weekend lis...,low
13473,Identity verification required: 756179 Your ac...,verify_code,identity verification required access code tra...,low
13474,Moderation notice: Community Guidelines update...,forum,moderation notice community guideline update t...,low
13475,Renew Google subscription 80% off Your package...,spam,renew google subscription package couldnt deli...,low
13476,Early access: Summer sale start now Final hour...,promotions,early access summer sale start final hour bigg...,low

In [23]:
df["urgency"].value_counts()

urgency
low       8973
medium    3036
high      1468
Name: count, dtype: int64

In [42]:
df = df[['clean_text', 'category', 'urgency']]
df.to_csv("final_preprocessed_dataset.csv", index=False)

In [31]:
from google.colab import files
files.download("final_preprocessed_dataset.csv")